server:
  port: 8002

spring:
  application:
    name: cloud-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/springcloudtb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mapper/*.xml  #寻找mapper.xml
  type-aliases-package: com.lc.springcloud.domain


eureka:
  client:
    #是否注册入eureka注册中心
    register-with-eureka: true
    #设置为true才能实现负载均衡
    fetch-registry: true
    #注册进去后的地址
    service-url:
#      defaultZone: http://localhost:7001/eureka
#      集群配置
       defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: PayMent8002
    prefer-ip-address: true